### ISSUE TITLE
No handler accepted "/"

### ISSUE THREAD

**Issue by schell** [tibbe/ekg#22]
I'm trying to make ekg accessible out in the open on a server using 

```
forkServer anIpAddress aPort
```

when visiting that ip address on that port I get `No handler accepted "/"`. Is this expected? If so, how do I use ekg remotely?

**Comment by ods94065** [comment]
Here's my story while running into this problem:

I'm using Stack to build a web app (including ekg) that I'm deploying inside a Docker container. In particular, I'm installing my app in a fresh container with no explicit Haskell dependencies (we'll see how that goes!). JSON API calls to EKG worked but HTML did not.

The problem was indeed that the directory of assets didn't exist in the runtime container, and `ekg` could not find it. This directory contains the files needed to provide the HTML interface, and Snap apparently raises this error when a file it's trying to serve can't be found (see https://github.com/snapframework/snap/issues/102 ).

The problem Sean mentions in https://github.com/tibbe/ekg/issues/48 bit me hard, since if his path to the assets directory was weird, mine using Stack/Docker is _really_ weird. I don't know an easy way to magic these files into my Docker installation, so I cheated: I'm pinning EKG for now and copying the `assets/` directory into my project.

One final note: You'll see that `ekg` appends `</> assets` to your data path, so make sure you're not setting your data directory to the assets directory itself! I installed my stuff in `/app/ekg-0.4.0.9/assets`, and set `ENV ekg_datadir=/app/ekg-0.4.0.9`. That was what did the trick.

**Comment by dysinger** [comment]
I just hit the same problem with stack and a docker-enabled project

**Comment by dysinger** [comment]
It might be better to use fileEmbed so that directories don't need to be found.

**Comment by lorenzo** [comment]
In case anyone is looking for a solution. I have this script for building the image:

```bash
	docker pull
	stack build
	find ~/.stack -name "assets" -exec cp -a {} shared_folder \;
	stack image container --build
```

This works with the following `stack.yaml` configuration:

```yaml
docker:
    enable: true
    repo: "fpco/stack-build"
    auto-pull: true
image:
  container:
    name: image-name
    base: fpco/stack-run
    add:
        shared_folder: /build_stuff
```

And when executed with this ENV var:

```
ekg_datadir=/build_stuff
```
